version: '2'
services:
    mygateway-mongodb:
        container_name: mygateway-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/myGateWay/mongodb/:/data/db/
